# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Backup script
(source ~/.backup_data &) > /dev/null 2>&1

export PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PYTHONPATH="$PYTHONPATH:/media/src/wopr/src/python/:/media/src/pyqtgraph/:/media/src/xwopr/"
export PYTHONPATH="$PYTHONPATH:/media/src/osbrain/"

xinput set-prop "USB OPTICAL MOUSE" "Device Accel Constant Deceleration" 2.5

