# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Conda virtual environment functions
workon() {
	source activate $1
}
deactivate() {
	source deactivate
}

# Conda
newpath=/cache/miniconda/bin
[[ ":$PATH:" != *":$newpath:"* ]] && export PATH="$PATH:$newpath"

# npm-packages
newpath=/container/npm-packages/bin
[[ ":$PATH:" != *":$newpath:"* ]] && export PATH="$PATH:$newpath"
