# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Conda virtual environment functions
workon() {
	source activate $1
}
deactivate() {
	source deactivate
}

# Custom /bin
export PATH=/media/bin:$PATH

# Conda
#export PATH="$(conda info --root)/bin:$PATH"
export PATH="~/.miniconda3/bin:$PATH"
