#!/bin/bash

DIR="$(cd "$(dirname "$0")" && pwd)"

# Vim
rm -f ~/.vimrc
ln -s $DIR/vimrc ~/.vimrc

# Terminator
rm -f ~/.config/terminator/config
ln -s $DIR/terminator ~/.config/terminator/config

# IPython
rm -f ~/.ipython/profile_default/ipython_config.py
ln -s $DIR/ipython_config.py ~/.ipython/profile_default/ipython_config.py

