#!/bin/bash

if [ "$(id -u)" == "0" ]; then
	echo "This script must not be run as root" 1>&2
	exit 1
fi

DIR="$(cd "$(dirname "$0")" && pwd)"

# Increase screencast max length in seconds (CTRL + ALT + MAYUS + R)
gsettings set org.gnome.settings-daemon.plugins.media-keys max-screencast-length 3600
# Set idle delay to 0
gsettings set org.gnome.desktop.session idle-delay 0

# GNOME settings
## Terminal
GSETTINGS_SCHEMA=org.gnome.Terminal.Legacy.Keybindings
GSETTINGS_PATH=/org/gnome/terminal/legacy/keybindings/
SCHEMA_PATH=$GSETTINGS_SCHEMA:$GSETTINGS_PATH
gsettings set $SCHEMA_PATH switch-to-tab-1 '<Primary><Alt>1'
gsettings set $SCHEMA_PATH switch-to-tab-2 '<Primary><Alt>2'
gsettings set $SCHEMA_PATH switch-to-tab-3 '<Primary><Alt>3'
gsettings set $SCHEMA_PATH switch-to-tab-4 '<Primary><Alt>4'
gsettings set $SCHEMA_PATH switch-to-tab-5 '<Primary><Alt>5'
gsettings set $SCHEMA_PATH switch-to-tab-6 '<Primary><Alt>6'
gsettings set $SCHEMA_PATH switch-to-tab-7 ''
gsettings set $SCHEMA_PATH switch-to-tab-8 ''
gsettings set $SCHEMA_PATH switch-to-tab-9 ''
gsettings set $SCHEMA_PATH switch-to-tab-10 ''
gsettings set $SCHEMA_PATH move-tab-left '<Primary><Alt>7'
gsettings set $SCHEMA_PATH move-tab-right '<Primary><Alt>8'
gsettings set $SCHEMA_PATH prev-tab '<Primary><Alt>9'
gsettings set $SCHEMA_PATH next-tab '<Primary><Alt>0'
SCHEMA=org.gnome.Terminal.Legacy.Settings
gsettings set $SCHEMA default-show-menubar false
gsettings set $SCHEMA menu-accelerator-enabled false
## Region
SCHEMA=org.gnome.system.locale
gsettings set $SCHEMA region 'en_DK.UTF-8'
## Clock
SCHEMA=org.gnome.desktop.interface
gsettings set $SCHEMA clock-format '24h'
gsettings set $SCHEMA clock-show-date true
gsettings set $SCHEMA clock-show-seconds false
# Language
SCHEMA=org.gnome.desktop.input-sources
gsettings set $SCHEMA sources "[('xkb', 'es'), ('xkb', 'us+dvorak')]"
# Keyboard shortcuts
SCHEMA=org.gnome.settings-daemon.plugins.media-keys
gsettings set $SCHEMA volume-mute "'AudioMute'"
gsettings set $SCHEMA volume-up "'AudioRaiseVolume'"
gsettings set $SCHEMA volume-down "'AudioLowerVolume'"
# Sound
SCHEMA=org.gnome.desktop.sound
gsettings set $SCHEMA event-sounds false
# Windows
SCHEMA=org.gnome.desktop.wm.preferences
gsettings set $SCHEMA action-middle-click-titlebar 'lower'

# .bash_profile
rm -f ~/.bash_profile
ln -s $DIR/bash_profile ~/.bash_profile

# .bashrc
rm -f ~/.bashrc
ln -s $DIR/bashrc ~/.bashrc

# .gitconfig
rm -f ~/.gitconfig
ln -s $DIR/gitconfig ~/.gitconfig

# User dirs
#rm -f ~/.config/user-dirs.dirs
#ln -s $DIR/user-dirs.dirs ~/.config/user-dirs.dirs

# Vim
rm -f ~/.vimrc
rm -rf ~/.vim
rm -rf ~/.config/nvim
ln -s $DIR/vimrc ~/.vimrc
ln -s $DIR/vim ~/.vim
ln -s $DIR/vim ~/.config/nvim

# Terminator
rm -f ~/.config/terminator/config
mkdir -p ~/.config/terminator
ln -s $DIR/terminator ~/.config/terminator/config

# IPython
rm -f ~/.ipython/profile_default/ipython_config.py
mkdir -p ~/.ipython/profile_default
ln -s $DIR/ipython_config.py ~/.ipython/profile_default/ipython_config.py

# Shotwell
rm -rf ~/.local/share/shotwell/data
rm -rf ~/.cache/shotwell/thumbs
mkdir -p ~/.local/share/shotwell
mkdir -p ~/.cache/shotwell
ln -s /mnt/album/.shotwell_data/ ~/.local/share/shotwell/data
ln -s /mnt/album/.shotwell_thumbs/ ~/.cache/shotwell/thumbs
