#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

# /usr/bin/workmode
LAUNCHER="/tmp/workmode"
echo -e '#/bin/bash
# Exit if no external monitor is connected
if [ -n "$(xrandr | grep DP1 | grep disconnected)" ]; then
	exit
fi
# Turn on/off the secondary display
if [ -n "$(xrandr | grep LVDS1 | grep +)" ]; then
    xrandr --output LVDS1 --off
    gsettings set org.gnome.desktop.session idle-delay 300
else
    xrandr --output DP1 --primary --pos 0x0 --output LVDS1 --auto --pos 1920x700
    gsettings set org.gnome.desktop.session idle-delay 0
fi' > $LAUNCHER
chmod +x $LAUNCHER
mv $LAUNCHER /usr/bin

