#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

cd $(dirname "$0")

ROOTDIR=$(pwd)

# Copy icons
cp $ROOTDIR/icons/* /usr/share/icons/hicolor/scalable/apps/

# Create Elliott launcher
echo "[Desktop Entry]
Type=Application
Terminal=false
Icon=/usr/share/icons/hicolor/scalable/apps/python-terminator.svg
Name=PyWorkspace
Exec=pyworkspace
Categories=Development;"> "/usr/share/applications/pyworkspace.desktop"
