#!/bin/bash

if [ "$(id -u)" == "0" ]; then
	echo "This script must not be run as root" 1>&2
	exit 1
fi

DIR="$(cd "$(dirname "$0")" && pwd)"

# Increase screencast max length in seconds (CTRL + ALT + MAYUS + R)
gsettings set org.gnome.settings-daemon.plugins.media-keys max-screencast-length 3600
# Set idle delay to 0
gsettings set org.gnome.desktop.session idle-delay 0

# Gnome terminal configuration
GSETTINGS_SCHEMA=org.gnome.Terminal.Legacy.Keybindings
GSETTINGS_PATH=/org/gnome/terminal/legacy/keybindings/
SCHEMA_PATH=$GSETTINGS_SCHEMA:$GSETTINGS_PATH
gsettings set $SCHEMA_PATH switch-to-tab-1 '<Primary><Alt>1'
gsettings set $SCHEMA_PATH switch-to-tab-2 '<Primary><Alt>2'
gsettings set $SCHEMA_PATH switch-to-tab-3 '<Primary><Alt>3'
gsettings set $SCHEMA_PATH switch-to-tab-4 '<Primary><Alt>4'
gsettings set $SCHEMA_PATH switch-to-tab-5 '<Primary><Alt>5'
gsettings set $SCHEMA_PATH switch-to-tab-6 '<Primary><Alt>6'
gsettings set $SCHEMA_PATH move-tab-left '<Primary><Alt>7'
gsettings set $SCHEMA_PATH move-tab-right '<Primary><Alt>8'
gsettings set $SCHEMA_PATH prev-tab '<Primary><Alt>9'
gsettings set $SCHEMA_PATH next-tab '<Primary><Alt>0'
GSETTINGS_SCHEMA=org.gnome.Terminal.Legacy.Settings
gsettings set $GSETTINGS_SCHEMA default-show-menubar false
gsettings set $GSETTINGS_SCHEMA menu-accelerator-enabled false

# .bash_profile
rm -f ~/.bash_profile
ln -s $DIR/bash_profile ~/.bash_profile

# .bashrc
rm -f ~/.bashrc
ln -s $DIR/bashrc ~/.bashrc

# .gitconfig
rm -f ~/.gitconfig
ln -s $DIR/gitconfig ~/.gitconfig

# User dirs
#rm -f ~/.config/user-dirs.dirs
#ln -s $DIR/user-dirs.dirs ~/.config/user-dirs.dirs

# Vim
rm -f ~/.vimrc
rm -rf ~/.vim
rm -rf ~/.config/nvim
ln -s $DIR/vimrc ~/.vimrc
ln -s $DIR/vim ~/.vim
ln -s $DIR/vim ~/.config/nvim

# Terminator
rm -f ~/.config/terminator/config
mkdir -p ~/.config/terminator
ln -s $DIR/terminator ~/.config/terminator/config

# IPython
rm -f ~/.ipython/profile_default/ipython_config.py
mkdir -p ~/.ipython/profile_default
ln -s $DIR/ipython_config.py ~/.ipython/profile_default/ipython_config.py

# Shotwell
rm -rf ~/.local/share/shotwell/data
rm -rf ~/.cache/shotwell/thumbs
mkdir -p ~/.local/share/shotwell
mkdir -p ~/.cache/shotwell
ln -s /data/Shotwell/.data/ ~/.local/share/shotwell/data
ln -s /data/Shotwell/.thumbs/ ~/.cache/shotwell/thumbs
