#!/bin/bash

DIR="$(cd "$(dirname "$0")" && pwd)"

# User dirs
rm -f ~/.config/user-dirs.dirs
ln -s $DIR/user-dirs.dirs ~/.config/user-dirs.dirs

# Vim
rm -f ~/.vimrc
rm -rf ~/.vim
ln -s $DIR/vimrc ~/.vimrc
ln -s $DIR/vim ~/.vim

# Terminator
rm -f ~/.config/terminator/config
ln -s $DIR/terminator ~/.config/terminator/config

# IPython
rm -f ~/.ipython/profile_default/ipython_config.py
ln -s $DIR/ipython_config.py ~/.ipython/profile_default/ipython_config.py

