#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

# Bash autocompletion rules
cp bash_completion.d/* /etc/bash_completion.d/

# /etc/fstab
#AUX="192.168.0.22:/mnt/HD/HD_a2"
#mkdir -p /nas/public
#echo "$AUX/Public /nas/public nfs rw,hard,intr,nofail 0 0" >> /etc/fstab
#mkdir -p /nas/uploads
#echo "$AUX/Uploads /nas/uploads nfs rw,hard,intr,nofail 0 0" >> /etc/fstab

# /aux
#mkdir -p /aux
#echo "/dev/disk/by-label/Aux /aux auto nosuid,nodev,nofail,x-gvfs-show 0 0" >> /etc/fstab

# Backups
#mkdir -p /backups
#echo "/dev/disk/by-label/Backups /backups auto nosuid,nodev,nofail,noauto 0 0" >> /etc/fstab

# Mount all
#mount -a
